// Mirrors the tab layout of the real HA dashboard (lovelace views: default_view,
// "P. N", "T1", "T2", "T3") — entity lists extracted directly from that dashboard's
// storage config so this app's tabs match what's actually on each physical floor,
// instead of a generic area-based grouping.
export interface ViewDef {
  id: string;
  label: string;
  entityIds: string[];
}

export const VIEWS: ViewDef[] = [
  {
    id: "home",
    label: "Home",
    entityIds: [
      "climate.aircon",
      "climate.ir_smart_hub_dieu_hoa_daikin",
      "cover.cua_cuon_zigbee",
      "input_number.duy_tri_nhiet_do",
      "media_player.kdl_43w800c",
      "script.cuacuon_dong",
      "script.cuacuon_mo",
      "script.cuacuon_stop",
      "script.dongtam",
      "script.mocua1p2",
      "script.mothoang",
      "script.tat_tat_cac_den",
      "sensor.0xa4c138e81699efa4_linkquality",
      "sensor.am_lich",
      "sensor.disk_use_percent_home",
      "sensor.drive_temp_one_2",
      "sensor.hass_mariadb_size",
      "sensor.last_boot",
      "sensor.memory_use_percent",
      "sensor.nhiet_do_bedroom",
      "sensor.o_cam_zigbee_20a_energy",
      "sensor.o_cam_zigbee_20a_linkquality",
      "sensor.o_cam_zigbee_20a_power",
      "sensor.o_cam_zigbee_20a_voltage",
      "sensor.processor_use",
      "sensor.proxmox_cpu_used",
      "sensor.quanghuy_cpu_utilization_user",
      "sensor.swap_use_percent",
      "switch.o_cam_zigbee_20a",
      "switch.sonoff_1000e2aa15",
      "switch.tat_mo_win_10",
    ],
  },
  {
    id: "pn",
    label: "P.N",
    entityIds: [
      "climate.aircon",
      "input_boolean.dieu_hoa_phong_ngu_duy_tri_tu_dong",
      "input_number.duy_tri_nhiet_do",
      "media_player.kdl_43w800c",
      "remote.kdl_43w800c",
      "script.bat_binhnonglanh_10p",
      "script.bat_binhnonglanh_15p",
      "script.bat_binhnonglanh_20p",
      "script.bat_binhnonglanh_30p",
      "script.bat_binhnonglanh_60p",
      "script.ir_mitomo_off",
      "script.ir_mitomo_on",
      "script.ir_mitomo_swing",
      "script.ir_mitomo_time",
      "sensor.0xa4c138159e4ff542_linkquality",
      "sensor.cam_bien_nhiet_do_sonoff_humidity",
      "sensor.nhiet_do_bedroom",
      "switch.binh_nong_lanh",
      "switch.den_cong_tac",
      "switch.den_ngu",
      "switch.den_nha_ve_sinh",
      "switch.den_nha_ve_sinh_2",
      "switch.den_phong_ngu",
      "switch.tat_mo_win_10",
    ],
  },
  {
    id: "t1",
    label: "T1",
    entityIds: [
      "script.bat_tat_den_tang_1",
      "script.cuacuon_dong",
      "script.cuacuon_mo",
      "script.cuacuon_stop",
      "script.ir_mibox_back",
      "script.ir_mibox_home",
      "script.ir_mibox_onoff",
      "script.ir_mibox_volume1",
      "script.ir_mibox_volume2",
      "script.ir_quattuong_t1_off",
      "script.ir_quattuong_t1_off_2",
      "script.ir_quattuong_t1_on_2",
      "script.ir_quattuong_t1_swing",
      "script.ir_quattuong_t1_swing_2",
      "script.ir_quattuong_t1_time",
      "script.ir_quattuong_t1_time_2",
      "script.quattuong_1",
      "script.quattuong_2",
      "script.quattuong_3",
      "script.tat_tat_den_tang_1",
      "sensor.nhiet_do_kitchen",
      "sensor.processor_use",
      "sensor.quanghuy_cpu_utilization_user",
      "switch.den_ban_hang",
      "switch.den_tang_1_2",
      "switch.den_trong_tang_1_switch_1",
      "switch.kitchen_0",
      "switch.kitchen_1",
      "switch.kitchen_2",
      "switch.nha_ve_sinh_tang_1_switch_1",
    ],
  },
  {
    id: "t2",
    label: "T2",
    entityIds: [
      "button.quanghuy_reboot",
      "button.quanghuy_shutdown",
      "climate.dieu_hoa_sk",
      "script.ir_mitomo_off_pro",
      "script.ir_mitomo_on_pro",
      "script.ir_mitomo_swing_pro",
      "script.ir_mitomo_time_pro",
      "script.ir_quat_tran_pk_den",
      "script.ir_quat_tran_pk_spd1",
      "script.ir_quat_tran_pk_spd2",
      "script.ir_quat_tran_pk_spd3",
      "script.ir_quat_tran_pk_stop",
      "script.ir_sk_off_pro",
      "script.ir_sk_on_pro",
      "sensor.drive_temp_one_2",
      "sensor.drive_temp_one_3",
      "sensor.proxmox_nvme_2",
      "switch.cau_thang_2",
      "switch.living2_room_lamp_1",
      "switch.living2_room_lamp_2",
      "switch.living_room_lamp_1",
      "switch.living_room_lamp_2",
      "switch.o_cam_xiaomi",
      "switch.proxmox_reboot_101",
      "switch.proxmox_switch",
      "switch.tat_mo_win_10",
    ],
  },
  {
    id: "t3",
    label: "T3",
    entityIds: [
      "sensor.cau_thang_4_linkquality",
      "sensor.o_cam_tuya_power",
      "sensor.o_cam_xiaomi_power",
      "sensor.proxmox_cpu_0",
      "sensor.proxmox_cpu_1",
      "sensor.quanghuy_volume_2_volume_used",
      "sensor.quanghuy_volume_3_volume_used",
      "switch.cau_thang_3",
      "switch.cau_thang_4_center",
      "switch.o_cam_tuya",
      "switch.tang3_recovery_solax3switch01_den_1",
      "switch.tang3_recovery_solax3switch01_den_2",
      "switch.tang3_recovery_solax3switch01_den_3",
    ],
  },
];
